GET http://localhost:5000/api/user/user-agent  HTTP/1.1

Content-Security-Policy : "upgrade-insecure-requests",
Strict-Transport-Security : "max-age=1000",
X-Xss-Protection : "1; mode=block",
X-Frame-Options : "DENY",
X-Content-Type-Options : "nosniff",
Referrer-Policy : "strict-origin-when-cross-origin"

###


DELETE http://localhost:5000/api/user/user-agent/656b791d2a0cdd8658916ed5 HTTP/1.1

###

'soft delete auser agent'
DELETE http://localhost:5000/api/user/soft-delete/users-agen/:id  HTTP/1.1


###
GET  http://localhost:5000/api/user/user-agent/1  HTTP/1.1

###
PUT  http://localhost:5000/api/user/soft-delete/users-agen/6574853757e338c56b110781  HTTP/1.1

###

'search on user agent'
GET  http://localhost:5000/api/user/search-users-agent  HTTP/1.1

###
GET  http://localhost:5000/api/user/soft-delete/users-agent  HTTP/1.1

###


POST http://localhost:5000/api/user/user-agent  HTTP/1.1
Content-Type: application/json

{
    "agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.76" ,
     "number":3
}

### 

'update a user agent'
PUT  http://localhost:5000/api/user/user-agent/656b44d5e74740b5992b6903  HTTP/1.1
Content-Type: application/json

{
     "number":5
}


###

